//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_exam_app.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int bill_id { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual order_ order_ { get; set; }
    }
}
