//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_exam_app.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_
    {
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> total_amount { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
        public virtual Users Users { get; set; }
    }
}
