//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_exam_app.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        public int provider_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string number_phone { get; set; }
        public string email { get; set; }
    }
}
