//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_exam_app.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.order_ = new HashSet<order_>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public string password_ { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public byte[] avatar { get; set; }
        public string desc_ { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string cmnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_> order_ { get; set; }
    }
}
